[default]

RFNTREES = 200 # Number of random trees;
RFBAGFRACTION = 0.5 # Fraction (10^-2%) of variables in the bag;
RFVARPERSPLIT = 6 # Number of varibales per tree branch;

# 
LANDSAT_GRID = "users/vieiramesquita/LAPIG-PASTURE/VECTORS/LANDSAT_GRID_V2_PASTURE"


COL5_TRAIN_DATA_PLANTED = 'users/vieiramesquita/mapbiomas_col3_1_all_stages_12_03_2018_past_cultivado_QGIS_new_pampa_v2'
COL6_TRAIN_DATA = "users/vieiramesquita/LAPIG-PASTURE/VECTORS/mapbiomas_col6_all_stages_10_06_2021_past_cultivado_and_natural_QGIS_v4"


B1 = "((b('B1')<0)*0 + (b('B1') > 1)*1 + (b('B1') >= 0 & b('B1') <= 1)*b('B1'))"
B2 = "((b('B2')<0)*0 + (b('B2') > 1)*1 + (b('B2') >= 0 & b('B2') <= 1)*b('B2'))"
B3 = "((b('B3')<0)*0 + (b('B3') > 1)*1 + (b('B3') >= 0 & b('B3') <= 1)*b('B3'))"
B4 = "((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4'))"
B5 = "((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5'))"
B6_L8 = "((b('B6')<0)*0 + (b('B6') > 1)*1 + (b('B6') >= 0 & b('B6') <= 1)*b('B6'))"
B7 = "((b('B7')<0)*0 + (b('B7') > 1)*1 + (b('B7') >= 0 & b('B7') <= 1)*b('B7'))"
CAI_L8 = "((b('B7')<0)*0 + (b('B7') > 1)*1 + (b('B7') >= 0 & b('B7') <= 1)*b('B7'))/((b('B6')<0)*0 + (b('B6') > 1)*1 + (b('B6') >= 0 & b('B6') <= 1)*b('B6'))"
CAI_L5_7 = "((b('B7')<0)*0 + (b('B7') > 1)*1 + (b('B7') >= 0 & b('B7') <= 1)*b('B7'))/((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5'))"
NDVI_L8 = "(((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')) - ((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')))/(((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')) + ((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')))"
NDWI_L8 = "(((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')) - ((b('B6')<0)*0 + (b('B6') > 1)*1 + (b('B6') >= 0 & b('B6') <= 1)*b('B6')))/(((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')) + ((b('B6')<0)*0 + (b('B6') > 1)*1 + (b('B6') >= 0 & b('B6') <= 1)*b('B6')))"
NDVI_L5_7 = "(((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')) - ((b('B3')<0)*0 + (b('B3') > 1)*1 + (b('B3') >= 0 & b('B3') <= 1)*b('B3')))/(((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')) + ((b('B3')<0)*0 + (b('B3') > 1)*1 + (b('B3') >= 0 & b('B3') <= 1)*b('B3')))"
NDWI_L5_7 = "(((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')) - ((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')))/(((b('B4')<0)*0 + (b('B4') > 1)*1 + (b('B4') >= 0 & b('B4') <= 1)*b('B4')) + ((b('B5')<0)*0 + (b('B5') > 1)*1 + (b('B5') >= 0 & b('B5') <= 1)*b('B5')))"

GRIDLIST = ['T001057','T001058','T001059','T001060','T001061',
'T001062','T001063','T001064','T001065','T001066','T001067','T002057',
'T002059','T002060','T002061','T002062','T002063','T002064','T002065',
'T002066','T002067','T002068','T003058','T003059','T003060','T003061',
'T003062','T003063','T003064','T003065','T003066','T003067','T003068',
'T004059','T004060','T004061','T004062','T004063','T004064','T004065',
'T004066','T004067','T005059','T005060','T005063','T005064','T005065',
'T005066','T005067','T006063','T006064','T006065','T006066','T214064',
'T214065','T214066','T214067','T215063','T215064','T215065','T215066',
'T215067','T215068','T215069','T215070','T215071','T215072','T215073',
'T215074','T216063','T216064','T216065','T216066','T216067','T216068',
'T216069','T216070','T216071','T216072','T216073','T216074','T216075',
'T216076','T217062','T217063','T217064','T217065','T217066','T217067',
'T217068','T217069','T217070','T217071','T217072','T217073','T217074',
'T217075','T217076','T218062','T218063','T218064','T218065','T218066',
'T218067','T218068','T218069','T218070','T218071','T218072','T218073',
'T218074','T218075','T218076','T218077','T219062','T219063','T219064',
'T219065','T219066','T219067','T219068','T219069','T219070','T219071',
'T219072','T219073','T219074','T219075','T219076','T219077','T220062',
'T220063','T220064','T220065','T220066','T220067','T220068','T220069',
'T220070','T220071','T220072','T220073','T220074','T220075','T220076',
'T220077','T220078','T220079','T220080','T220081','T220082','T221061',
'T221062','T221063','T221064','T221065','T221066','T221067','T221068',
'T221069','T221070','T221071','T221072','T221073','T221074','T221075',
'T221076','T221077','T221078','T221079','T221080','T221081','T221082',
'T221083','T222061','T222062','T222063','T222064','T222065','T222066',
'T222067','T222068','T222069','T222070','T222071','T222072','T222073',
'T222074','T222075','T222076','T222077','T222078','T222079','T222080',
'T222081','T222082','T222083','T223060','T223061','T223062','T223063',
'T223064','T223065','T223066','T223067','T223068','T223069','T223070',
'T223071','T223072','T223073','T223074','T223075','T223076','T223077',
'T223078','T223079','T223080','T223081','T223082','T224060','T224061',
'T224062','T224063','T224064','T224065','T224066','T224067','T224068',
'T224069','T224070','T224071','T224072','T224073','T224074','T224075',
'T224076','T224077','T224078','T224079','T224080','T224081','T224082',
'T225058','T225059','T225060','T225061','T225062','T225063','T225064',
'T225065','T225066','T225067','T225068','T225069','T225070','T225071',
'T225072','T225073','T225074','T225075','T225076','T225077','T225080',
'T225081','T226057','T226058','T226059','T226060','T226061','T226062',
'T226063','T226064','T226065','T226066','T226067','T226068','T226069',
'T226070','T226071','T226072','T226073','T226074','T226075','T227058',
'T227059','T227060','T227061','T227062','T227063','T227064','T227065',
'T227066','T227067','T227068','T227069','T227070','T227071','T227072',
'T227073','T227074','T227075','T228058','T228059','T228060','T228061',
'T228062','T228063','T228064','T228065','T228066','T228067','T228068',
'T228069','T228070','T228071','T228072','T229058','T229059','T229060',
'T229061','T229062','T229063','T229064','T229065','T229066','T229067',
'T229068','T229069','T229070','T229071','T230059','T230060','T230061',
'T230062','T230063','T230064','T230065','T230066','T230067','T230068',
'T230069','T231057','T231058','T231059','T231060','T231061','T231062',
'T231063','T231064','T231065','T231066','T231067','T231068','T231069',
'T232056','T232057','T232058','T232059','T232060','T232061','T232062',
'T232063','T232064','T232065','T232066','T232067','T232068','T232069',
'T233057','T233058','T233059','T233060','T233061','T233062','T233063',
'T233064','T233065','T233066','T233067','T233068']


[collection5]
START_YEAR = 1985
END_YEAR = 2017
FOLDER = "Pasture_Mapping_Landsat_Col5"

[collection6]
START_YEAR = 2018
END_YEAR = 2020
FOLDER = "Pasture_Mapping_Landsat_Col6"

